### ISSUE TITLE
Ed Dashboard

### ISSUE THREAD

**Issue by hunterjsb** [we-be/c7#1]
## Issue
We need to build a dashboard for @edfarialand to grade and review phones before Claude initiates the conversation. This dashboard will display all listings stored in `c3` and reflect his changes.

## Implementation
- [x] #2 
- [x] #3 
- [x] #4

**Comment by hunterjsb** [comment]
- [ ] #7

**Comment by hunterjsb** [comment]
- [ ] #10 
- [ ] Create crypto wallet @LePogoZ 🏦

**Comment by edfarialand** [comment]
Everything is working pretty much how I want it. Hunter knows of all the changes I want and they’re aren’t many. Pretty much just 

automate the list refresh/take rated phones out the queue


weird. I just understood the reasoning behind the listing being minimized 
auto toggle all listings to expanded. 
remove previous 
remove next from 
Or
make next faster 


change lcd damage to bad battery 

Bonus: make all buttons look like previous and next buttons on bottom

**Comment by hunterjsb** [comment]
We need to add pagination or something to make loading smoother when there are a lot of devices - we need to add like a next / previous page button so we can paginate. And I think we need autosave.
